### 1. 전체 예약 조회 (GET)
# @name getReservations
GET http://localhost:8080/reservations

### 2. 예약 추가 (POST)
# @name createReservation
POST http://localhost:8080/reservations
Content-Type: application/json

{
  "name": "브라운",
  "date": "2023-08-05",
  "time": "15:40"
}
