# DB connection setting
spring.datasource.url=jdbc:h2:mem:roomescape_database
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Activate h2-console
spring.h2.console.enabled=true
# Activate DB Schema initialization (using resources/scheme.sql File)
spring.jpa.defer-datasource-initialization=true