CREATE TABLE reservation
(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    date VARCHAR(255) NOT NULL,
    time VARCHAR(255) NOT NULL
);

CREATE TABLE reservation_time
(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    start_at VARCHAR(255) NOT NULL
);
