### 예약 추가
POST localhost:8080/reservations
Content-Type: application/json

{
  "name": "dompoo",
  "date": "2024-12-05",
  "time": "20:00"
}

### 예약 전체 조회

GET localhost:8080/reservations

### 예약 삭제

DELETE localhost:8080/reservations/1
