package roomescape.reservation.infrastructure.fake;

import java.time.LocalTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import roomescape.reservation.application.repository.ReservationTimeRepository;
import roomescape.reservation.domain.aggregate.ReservationTime;

public class FakeReservationTimeDao implements ReservationTimeRepository {

    private Long autoGeneratedId = 0L;
    private final Map<Long, ReservationTime> store = new HashMap<>();

    @Override
    public ReservationTime insert(LocalTime time) {
        autoGeneratedId++;
        ReservationTime reservationTime = new ReservationTime(autoGeneratedId, time);
        store.put(autoGeneratedId, reservationTime);

        return reservationTime;
    }

    @Override
    public List<ReservationTime> findAllTimes() {
        return store.values().stream().toList();
    }

    @Override
    public Optional<ReservationTime> findById(Long timeId) {
        return store.values().stream()
                .filter(reservationTime -> reservationTime.getId().equals(timeId))
                .findAny();
    }

    @Override
    public void delete(Long timeId) {
        store.remove(timeId);

        for (ReservationTime allTime : findAllTimes()) {
            System.out.println("allTime.getId() = " + allTime.getId());
        }
    }
}
