package roomescape.reservation.infrastructure.fake;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import roomescape.reservation.application.dto.CreateReservationRequest;
import roomescape.reservation.application.repository.ReservationRepository;
import roomescape.reservation.domain.aggregate.Reservation;

public class FakeReservationDao implements ReservationRepository {

    private Long autoGeneratedId = 0L;
    private final Map<Long, Reservation> store = new HashMap<>();

    @Override
    public Reservation insert(CreateReservationRequest request) {
        autoGeneratedId++;
        Reservation reservation = new Reservation(autoGeneratedId,
                request.getName(),
                request.getDate(),
                request.getTime()
        );
        store.put(autoGeneratedId, reservation);

        return reservation;
    }

    @Override
    public List<Reservation> findAllReservations() {
        return store.values().stream().toList();
    }

    @Override
    public void delete(Long reservationId) {
        store.remove(reservationId);
    }
}
