package roomescape.fake;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.concurrent.atomic.AtomicLong;
import roomescape.domain.reservation.entity.Reservation;
import roomescape.domain.reservation.repository.ReservationRepository;

public class FakeReservationRepository implements ReservationRepository {

    private final List<Reservation> reservations = new ArrayList<>();
    private final AtomicLong autoGeneratedId = new AtomicLong(1);

    @Override
    public List<Reservation> findAll() {
        return new ArrayList<>(reservations);
    }

    @Override
    public Reservation save(Reservation reservation) {
        reservation.setId(autoGeneratedId.getAndIncrement());
        reservations.add(reservation);
        return reservation;
    }

    @Override
    public void deleteById(Long id) {
        reservations.removeIf(r -> Objects.equals(r.getId(), id));
    }
}
