package roomescape.fake;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicLong;
import roomescape.domain.reservation.entity.ReservationTime;
import roomescape.domain.reservation.repository.ReservationTimeRepository;

public class FakeReservationTimeRepository implements ReservationTimeRepository {

    private final List<ReservationTime> reservationTimes = new ArrayList<>();
    private final AtomicLong autoGeneratedId = new AtomicLong(1);

    @Override
    public List<ReservationTime> findAll() {
        return new ArrayList<>(reservationTimes);
    }

    @Override
    public Optional<ReservationTime> findById(Long id) {
        return reservationTimes.stream()
                .filter(time -> id.equals(time.getId()))
                .findFirst();
    }

    @Override
    public ReservationTime save(ReservationTime reservationTime) {
        reservationTime.setId(autoGeneratedId.getAndIncrement());
        reservationTimes.add(reservationTime);
        return reservationTime;
    }

    @Override
    public void deleteById(Long id) {
        reservationTimes.removeIf(time -> Objects.equals(time.getId(), id));
    }
}
